export const dummyDishes = [
  //fruits
  {
    id: 1,
    name: "Orange",
    image: require("../assets/Dishes/Fruits/orange.png"),
    type: "fruit",
    trending: false,
    price: 299,
    description: "Juicy from Farm",
  },
  {
    id: 2,
    name: "Pineapple",
    image: require("../assets/Dishes/Fruits/pineapple.png"),
    type: "fruit",
    trending: false,
    price: 299,
    description: "Freshly Imported",
  },
  {
    id: 3,
    name: "Strawberry",
    image: require("../assets/Dishes/Fruits/strawberry.png"),
    type: "fruit",
    trending: false,
    price: 299,
    description: "As red as it can be",
  },
  {
    id: 4,
    name: "Green Apple",
    image: require("../assets/Dishes/Fruits/greenapple.png"),
    type: "fruit",
    trending: false,
    price: 299,
    description: "Green Sweet",
  },
  {
    id: 5,
    name: "Grapes",
    image: require("../assets/Dishes/Fruits/grapes.png"),
    type: "fruit",
    trending: false,
    price: 299,
    description: "Fresh and Form",
  },
  {
    id: 6,
    name: "Cherry",
    image: require("../assets/Dishes/Fruits/cherry.png"),
    type: "fruit",
    trending: false,
    price: 299,
    description: "Sweet Sweet",
  },
  {
    id: 7,
    name: "Mango",
    image: require("../assets/Dishes/Fruits/mago.png"),
    type: "fruit",
    trending: false,
    price: 299,
    description: "King of Fruits",
  },
  {
    id: 8,
    name: "Guava",
    image: require("../assets/Dishes/Fruits/guava.png"),
    type: "fruit",
    trending: false,
    price: 299,
    description: "Green Out, Red In",
  },
  {
    id: 9,
    name: "Pomegranate",
    image: require("../assets/Dishes/Fruits/pomegranate.png"),
    type: "fruit",
    trending: false,
    price: 299,
    description: "Red marbles",
  },
  {
    id: 10,
    name: "Apple",
    image: require("../assets/Dishes/Fruits/apple.png"),
    type: "fruit",
    trending: false,
    price: 299,
    description: "Bye Bye Doctor",
  },

  // vegetables
  {
    id: 11,
    name: "Bell Pepper",
    image: require("../assets/Dishes/Vegetables/bellpepper.png"),
    type: "vegetable",
    trending: false,
    price: 299,
    description: "Juicy from Farm",
  },
  {
    id: 12,
    name: "broccoli",
    image: require("../assets/Dishes/Vegetables/broccoli.png"),
    type: "vegetable",
    trending: true,
    price: 299,
    description: "Freshly Imported",
  },
  {
    id: 13,
    name: "Cabbage",
    image: require("../assets/Dishes/Vegetables/cabbage.png"),
    type: "vegetable",
    trending: true,
    price: 299,
    description: "As red as it can be",
  },
  {
    id: 14,
    name: "Carrot",
    image: require("../assets/Dishes/Vegetables/carrot.png"),
    type: "vegetable",
    trending: true,
    price: 299,
    description: "Green Sweet",
  },
  {
    id: 15,
    name: "Egg Plant",
    image: require("../assets/Dishes/Vegetables/eggplant.png"),
    type: "vegetable",
    trending: true,
    price: 299,
    description: "Fresh and Form",
  },
  {
    id: 16,
    name: "Onion",
    image: require("../assets/Dishes/Vegetables/onion.png"),
    type: "vegetable",
    trending: true,
    price: 299,
    description: "Sweet Sweet",
  },
  {
    id: 17,
    name: "Parsley",
    image: require("../assets/Dishes/Vegetables/parsley.png"),
    type: "vegetable",
    trending: false,
    price: 299,
    description: "King of Vegetables",
  },
  {
    id: 18,
    name: "Sweat Peas",
    image: require("../assets/Dishes/Vegetables/peas.png"),
    type: "vegetable",
    trending: false,
    price: 299,
    description: "Green Out, Red In",
  },
  {
    id: 19,
    name: "Potato",
    image: require("../assets/Dishes/Vegetables/potato.png"),
    type: "vegetable",
    trending: false,
    price: 299,
    description: "Red marbles",
  },
  {
    id: 20,
    name: "Tomato",
    image: require("../assets/Dishes/Vegetables/tomato.png"),
    type: "vegetable",
    trending: false,
    price: 299,
    description: "Bye Bye Doctor",
  },

  // meals
  {
    id: 21,
    name: "Biryani",
    image: require("../assets/Dishes/Meals/biryani.png"),
    type: "meal",
    trending: true,
    price: 299,
    description: "Bye Bye Doctor",
  },
  {
    id: 22,
    name: "Burger",
    image: require("../assets/Dishes/Meals/burger.png"),
    type: "meal",
    trending: false,
    price: 299,
    description: "Bye Bye Doctor",
  },
  {
    id: 23,
    name: "Dosa",
    image: require("../assets/Dishes/Meals/dosa.png"),
    type: "meal",
    trending: true,
    price: 299,
    description: "Bye Bye Doctor",
  },
  {
    id: 24,
    name: "Fries",
    image: require("../assets/Dishes/Meals/fries.png"),
    type: "meal",
    trending: true,
    price: 299,
    description: "Bye Bye Doctor",
  },
  {
    id: 25,
    name: "Kabab",
    image: require("../assets/Dishes/Meals/kabab.png"),
    type: "meal",
    trending: true,
    price: 299,
    description: "Bye Bye Doctor",
  },
  {
    id: 26,
    name: "KFC",
    image: require("../assets/Dishes/Meals/kfc.png"),
    type: "meal",
    trending: false,
    price: 299,
    description: "Bye Bye Doctor",
  },
  {
    id: 27,
    name: "Pizza",
    image: require("../assets/Dishes/Meals/pizza.png"),
    type: "meal",
    trending: true,
    price: 299,
    description: "Bye Bye Doctor",
  },
  {
    id: 28,
    name: "Samosa",
    image: require("../assets/Dishes/Meals/samosa.png"),
    type: "meal",
    trending: true,
    price: 299,
    description: "Bye Bye Doctor",
  },
  {
    id: 29,
    name: "Cuisine",
    image: require("../assets/Dishes/Meals/vegetariancuisine.png"),
    type: "meal",
    trending: false,
    price: 299,
    description: "Bye Bye Doctor",
  },
  {
    id: 30,
    name: "Steak",
    image: require("../assets/Dishes/Meals/steak.png"),
    type: "meal",
    trending: true,
    price: 299,
    description: "Bye Bye Doctor",
  },
];
